general:
  site_url: 
  address:
  email:
  phone:
  social:
    - channel: "Facebook"
      add_to_chat_bubble: false
      url: 'https://facebook.com'
    - channel: "WhatsApp"
      add_to_chat_bubble: true
      url: 'https://facebook.com'
    - channel: "Messenger"
      add_to_chat_bubble: true
      url: 'https://facebook.com'
branding:
  site_title: Jekyll CloudCannon Boilerplate
  nav_logo_image: /assets/images/logo.png
  footer_logo_image:
  preview_image:
theme_settings:
  light_color: '#f2f2f2'
  dark_color: '#000000'
  accent_color: '#415a3d'
  complementary_color: '#2f2f2f'
  body_font_family: 'DINPro, sans-serif'
  heading_font_family: 'DINPro, sans-serif'
  body_font_size_number: 1.1rem
  line_height_number: 1.8
navigation:
  menus:
    - name: About
      url: /about
      is_dropdown: false
      style_as_button: false
      submenus:
        - name:
          url:
    - name: Dropdown
      url: '#'
      is_dropdown: true
      style_as_button: false
      submenus:
        - name: Item 1
          url: /
        - name: Item 2
          url: /
        - name: Item 3
          url: /
    - name: More
      url: '#'
      is_dropdown: true
      style_as_button: false
      submenus:
        - name: Item 1
          url: /
        - name: Item 2
          url: /
        - name: Item 3
          url: /
seo:
  site_description_text:
  keywords:
configuration:
  head_code_block: '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css">'
  body_code_block: >-
    